CONFIG_PM=n

CONFIG_MAIN_STACK_SIZE=15360
CONFIG_MBEDTLS_CFG_FILE="mcuboot-mbedtls-cfg.h"

CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_ENCRYPT_IMAGE=n
CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
# CONFIG_BOOT_ENCRYPT_RSA=y
# CONFIG_BOOT_ENCRYPT_EC256=n
# CONFIG_BOOT_ENCRYPT_X25519=n

# Secure Immutable Boot
# CONFIG_SECURE_BOOT=y
# CONFIG_SB_SIGNING_KEY_FILE="C:/01_testing/sibel-workspace/Anne-Aria/app/aria-priv_a.pem"
# CONFIG_SB_PUBLIC_KEY_FILES="C:/01_testing/sibel-workspace/Anne-Aria/app/aria-pub_ba.pem,C:/01_testing/sibel-workspace/Anne-Aria/app/aria-pub_ca.pem"

# CONFIG_BUILD_S1_VARIANT=y
# CONFIG_SB_SIGNING_KEY_FILE="aria-priv_d.pem"
# # CONFIG_SB_PUBLIC_KEY_FILES="aria-pub_ca.pem"
# CONFIG_FW_INFO_FIRMWARE_VERSION=2

CONFIG_BOOT_UPGRADE_ONLY=y
CONFIG_BOOT_BOOTSTRAP=n
CONFIG_MULTITHREADING=y
CONFIG_BOOT_MAX_IMG_SECTORS= 256

### mbedTLS has its own heap
# CONFIG_HEAP_MEM_POOL_SIZE is not set

### We never want Zephyr's copy of tinycrypt.  If tinycrypt is needed,
### MCUboot has its own copy in tree.
# CONFIG_TINYCRYPT is not set
# CONFIG_TINYCRYPT_ECC_DSA is not set
# CONFIG_TINYCRYPT_SHA256 is not set

CONFIG_FLASH=y
CONFIG_FPROTECT=y
CONFIG_SPI=y
CONFIG_MCUBOOT_SPI_NAND=y

### Various Zephyr boards enable features that we don't want.
# CONFIG_BT is not set
# CONFIG_BT_CTLR is not set
# CONFIG_I2C is not set

CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y # former CONFIG_MODE_MINIMAL
### Ensure Zephyr logging changes don't use more resources
CONFIG_LOG_DEFAULT_LEVEL=0
### Decrease footprint by ~4 KB in comparison to CBPRINTF_COMPLETE=y
CONFIG_CBPRINTF_NANO=y
CONFIG_NRF_RTC_TIMER_USER_CHAN_COUNT=0

#Adding the custom key for encryption
CONFIG_BOOT_SIGNATURE_KEY_FILE="aria-mcuboot-key.pem"
