# Cppcheck CI-CD
name: Cppcheck CI-CD

on:
  schedule:
    - cron: '*/7 * * * *'  # Runs every minute
  push:
    branches:
      - develop      # Runs on develop branch (including merges)
      # - '**'      # Runs on all branches (including merges)
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '.github/workflows/run_cppcheck.yml'  # Include workflow file itself
  pull_request:
    branches:
      - develop      # Runs on develop branch (including merges)
      # - '**'      # Runs on all branches (including merges)
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '.github/workflows/run_cppcheck.yml'  # Include workflow file itself

jobs:
  cppcheck_Anne-Aria:
    runs-on: ubuntu-20.04  # Use Ubuntu 20.04 for consistency

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up environment and install dependencies
        run: |
          sudo apt update
          sudo apt install -y cppcheck python3 python3-pip
          pip3 install lxml  # Install lxml (needed for cppcheck-htmlreport)

      - name: Generate IST Timestamp
        run: |
          IST_TIMESTAMP=$(TZ='Asia/Kolkata' date +"%Y-%m-%d_%H-%M-%S")
          echo "IST_TIMESTAMP=$IST_TIMESTAMP" >> $GITHUB_ENV

      - name: Print Current Working Directory (pwd)
        run: |
          echo "Current working directory: $(pwd)"
          ls -al

      - name: Run cppcheck and generate reports
        run: |
          REPORT_DIR="Anne-Aria_cppcheck-reports-${{ env.IST_TIMESTAMP }}"
          mkdir -p $REPORT_DIR

          XML_REPORT_FILE="$REPORT_DIR/Anne-Aria_cppcheck-report.xml"
          cppcheck $(pwd) \
          --xml \
          --output-file=$XML_REPORT_FILE \
          --enable=warning,performance,portability,style

          # Generate HTML report inside the same directory
          cppcheck-htmlreport --file=$XML_REPORT_FILE \
            --title="Cppcheck Analysis Report Anne-Aria" \
            --report-dir=$REPORT_DIR/HTML_REPORT

          echo "REPORT_DIR=$REPORT_DIR" >> $GITHUB_ENV

      - name: Upload cppcheck reports as artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Anne-Aria_cppcheck-reports-${{ env.IST_TIMESTAMP }}
          path: ${{ env.REPORT_DIR }}
      - name: Print Current Working Directory (pwd)
        run: |
          echo "Current working directory: $(pwd)"
          ls -al